### ISSUE TITLE
How to add extra Extensions?

### ISSUE THREAD

**Issue by BobWs** [arugifa/standardnotes-server-docker#3]
Any thoughts on how to add extra Extensions?

**Comment by arugifa** [comment]
As the base version of Standard Notes is enough for me, I never though about it to be honest :)

However, after reading the [doc](https://docs.standardnotes.org/extensions/local-setup/), I see that in order to use extensions, one should run a web server, aside the Standard Notes server, in order to host these extensions.

By using Docker volumes or mount-points, it should be feasible to store the extensions locally, and run a web server like Nginx inside Docker to serve the extensions.

**Comment by BobWs** [comment]
Thanks For your answer I have manage to install the extensions via this repo https://github.com/JokerQyou/snextensions
All the extensions are working for now :-)

**Comment by arugifa** [comment]
Nice :sunglasses: Thanks for the tip :+1:
